version: "3.4"
services:
  app:
    build:
      context: "."
      target: web
    image: registry.heroku.com/cslgbt-mentor-match/web:${GH_IMAGE_COMMIT_TAG}
    environment:
      - ENV=${ENV}

  worker:
    build:
      context: "."
      target: worker
    image: registry.heroku.com/cslgbt-mentor-match/worker:${GH_IMAGE_COMMIT_TAG}
