version: "3"
services:
  app:
    volumes:
      - ./mentor_match_web/app:/app
    environment:
      - USERNAME=CSLGBT
      - PASSWORD=HorseBatteryStapleCorrect

  jekyll:
    build:
      context: "./docs/"
    ports:
      - "4000:4000"
    volumes:
      - ./docs:/srv/jekyll
