version: '3'

services:
  redis:
    image: redis:6.0.15
    ports:
      - "6379:6379"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  app:
    build:
      context: "."
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./app:/app
