name: Deploy to Heroku

on:
  push:
    branches:
      - main
jobs:
  heroku-push-and-release:
    runs-on: ubuntu-20.04
    env:
      HEROKU_API_KEY: ${{ github.secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ github.secrets.HEROKU_EMAIL }}
    steps:
      - name: Push images to Heroku
        run: |
          heroku container:login
      - name: Deploy to Heroku
        run: heroku container:release web worker --app cslgbt-mentor-match
