name: Deploy to Heroku

on:
  push:
    branches:
      - main
jobs:
  bump-version:
    runs-on: ubuntu-latest
    env:
      DEFAULT_BUMP: minor
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        uses: jaumann/github-bumpversion-action@v0.0.7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true


  heroku-push-and-release:
    runs-on: ubuntu-20.04
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
    steps:
      - name: Push images to Heroku
        run: |
          heroku container:login
      - name: Deploy to Heroku
        run: heroku container:release web worker --app cslgbt-mentor-match
