name: Integrate and deploy
on:
  pull_request:

env:
  REDIS_URL: redis@redis
jobs:
  well-written-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2.4.0
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install mypy flake8 pytest pytest-cov

      - name: Test with mypy
        run: mypy tests/ app/ --ignore-missing-imports

      - name: Test with flake8
        run: flake8 --max-line-length=131 --extend-ignore=E203 tests/ app/


  get-commit-tag:
    needs: well-written-test
    runs-on: ubuntu-20.04
    outputs:
      image_commit_tag: ${{ steps.vars.outputs.image_commit_tag }}
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "::set-output name=image_commit_tag::$(git rev-parse --short HEAD)"


  all-tests:
    needs:
      - get-commit-tag
    env:
      ENV: integration
      GH_IMAGE_COMMIT_TAG: ${{ needs.get-commit-tag.outputs.image_commit_tag }}
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2.4.0
      - name: Install docker-compose
        if: ${{ env.ACT }}
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.27.4/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Compose environment
        run: docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d

      - name: Full test suite
        run: docker-compose exec -T app pytest tests --cache-clear --cov=app tests/ > pytest-coverage.txt

      - name: Comment coverage
        uses: coroo/pytest-coverage-commentator@v1.0.2

      - name: Stop docker
        if: ${{ env.ACT }}
        run: docker-compose down

      - name: Push to Heroku registry
        run: |
          docker login --username=${{ secrets.HEROKU_EMAIL }} --password-stdin <<< "${{ secrets.HEROKU_API_KEY }}" registry.heroku.com
          docker tag web:${{ needs.get-commit-tag.outputs.image_commit_tag }} registry.heroku.com/cslgbt-mentor-match/web
          docker tag worker:${{ needs.get-commit-tag.outputs.image_commit_tag }} registry.heroku.com/cslgbt-mentor-match/worker
          docker push registry.heroku.com/cslgbt-mentor-match/web
          docker push registry.heroku.com/cslgbt-mentor-match/worker
